#include "test-cxxbridge-api/src/cxx/mod.rs.h" // generated by cxx.rs
#include "rust/cxx.h" // provided by cxx.rs
#include "device.h"

namespace cxx::device {

  auto fetch_device(rust::usize num) -> std::shared_ptr<Device> {
    auto list = ::device::list_of_devices();
    auto device = list.at(num);
    return device;
  }

  auto fetch_hsm(rust::usize num) -> std::shared_ptr<HSM> {
    auto list = ::device::list_of_devices();
    auto device = list.at(num);
    return std::dynamic_pointer_cast<HSM>(device);
  }

} // namespace
